---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/srvcixvu/public_html/sites/shoprent.org.in/bilaspur
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - cd $DEPLOYPATH
    - /usr/local/bin/php $DEPLOYPATH/artisan migrate --force
    - /usr/local/bin/php $DEPLOYPATH/artisan config:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan route:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan view:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan key:generate
    - /usr/local/bin/php $DEPLOYPATH/artisan cache:clear
